apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-managed-project

resources:
  - vote-ui-deployment.yaml
  - vote-ui-service.yaml
  - vote-ui-route.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/gitops-managed-project/pipelines-vote-ui
    digest: 'sha256:0e8039d182161ecd2224b7f29faaf9932a9a3184fb4dfc69942c22e54c114f75'
