apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-managed-project

resources:
  - vote-ui-deployment.yaml
  - vote-ui-service.yaml
  - vote-ui-route.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/gitops-managed-project/pipelines-vote-ui
    digest: 'sha256:543af3e314b1546ca54e1bf942afbdf34853f19d1c84f6647cb8103f9798abb6'
