apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-managed-project

resources:
  - vote-ui-deployment.yaml
  - vote-ui-service.yaml
  - vote-ui-route.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/gitops-managed-project/pipelines-vote-ui
    digest: 'sha256:5712058ab81c9cd6a4dda7338631bd7371e8f29f3b501a4f563edce650afa195'
