apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
  namespace: gitops-managed-project
  labels:
    app: vote-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
        - name: vote-ui
          image: image-registry.openshift-image-registry.svc:5000/gitops-managed-project/pipelines-vote-ui@sha256:f9d941a4139af9cd18b0cef60bbb4491496c275ff5e10a43d67a65167b7984cc
          imagePullPolicy: Always
          env:
            - name: VOTING_API_SERVICE_HOST
              value: pipelines-vote-api
            - name: VOTING_API_SERVICE_PORT
              value: "9000"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
